"""PDF generation for student admission forms."""

from __future__ import annotations

import os
import datetime as _datetime
from pathlib import Path
from textwrap import wrap

from models.student import Student


class PDFService:
    """Creates a simple formatted PDF admission form without external dependencies."""

    PAGE_WIDTH = 595.28
    PAGE_HEIGHT = 841.89

    def __init__(self, output_dir: str | Path | None = None) -> None:
        if output_dir:
            self.output_dir = Path(output_dir)
        else:
            app_data_dir = os.environ.get("PARISHILON_ACADEMY_DATA_DIR")
            self.output_dir = Path(app_data_dir) / "pdfs" if app_data_dir else Path(__file__).resolve().parents[1] / "pdfs"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_admission_pdf(self, student: Student) -> Path:
        file_name = self._build_file_name(student)
        pdf_path = self.output_dir / file_name

        content_stream = self._build_content_stream(student)
        pdf_path.write_bytes(self._build_pdf_bytes(content_stream))
        return pdf_path

    def generate_fee_statement_pdf(self, student: Student, payment_records: list[dict[str, object]]) -> Path:
        file_name = self._build_fee_statement_file_name(student)
        pdf_path = self.output_dir / file_name

        content_stream = self._build_fee_statement_content_stream(student, payment_records)
        pdf_path.write_bytes(self._build_pdf_bytes(content_stream))
        return pdf_path

    def _build_file_name(self, student: Student) -> str:
        safe_name = "_".join(student.student_name.split())[:40] or "student"
        timestamp = _datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"admission_form_{student.id or 'new'}_{safe_name}_{timestamp}.pdf"

    def _build_fee_statement_file_name(self, student: Student) -> str:
        safe_name = "_".join(student.student_name.split())[:30] or "student"
        timestamp = _datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"fee_statement_{student.id or 'new'}_{safe_name}_{timestamp}.pdf"

    def _build_content_stream(self, student: Student) -> str:
        lines: list[str] = []

        def add_text(x: float, y: float, text: str, size: int = 11, color: tuple[float, float, float] = (0.0, 0.0, 0.0)) -> None:
            escaped_text = self._escape_text(self._ascii_safe(text))
            lines.append(f"BT /F1 {size} Tf {color[0]:.3f} {color[1]:.3f} {color[2]:.3f} rg 1 0 0 1 {x:.2f} {y:.2f} Tm ({escaped_text}) Tj ET")

        def add_wrapped_block(x: float, y: float, label: str, value: str, width: int = 60) -> float:
            add_text(x, y, f"{label}:", 11, (0.07, 0.11, 0.2))
            wrapped_lines = wrap(self._ascii_safe(value), width=width) or [""]
            add_text(x + 126, y, wrapped_lines[0], 11, (0.22, 0.25, 0.31))
            next_y = y - 18
            for continuation in wrapped_lines[1:]:
                add_text(x + 126, next_y, continuation, 11, (0.22, 0.25, 0.31))
                next_y -= 18
            return next_y

        lines.append("0.11 0.30 0.85 rg 36 746 523 58 re f")
        add_text(54, 776, "Student Admission Form", 18, (1, 1, 1))
        add_text(54, 758, "Parishilon Academy", 10, (0.93, 0.96, 1))
        add_text(470, 776, f"ID: {student.id or 'N/A'}", 10, (1, 1, 1))

        cursor_y = 700
        cursor_y = add_wrapped_block(54, cursor_y, "Student Name", student.student_name)
        cursor_y = add_wrapped_block(54, cursor_y, "S.I.N", student.sin)
        cursor_y = add_wrapped_block(54, cursor_y, "Father Name", student.father_name)
        cursor_y = add_wrapped_block(54, cursor_y, "Mother Name", student.mother_name)
        cursor_y = add_wrapped_block(54, cursor_y, "Phone Number", student.phone)
        cursor_y = add_wrapped_block(54, cursor_y, "School Name", student.school)
        cursor_y = add_wrapped_block(54, cursor_y, "Class", student.class_name)
        cursor_y = add_wrapped_block(54, cursor_y, "Admission Date", student.admission_date)
        cursor_y = add_wrapped_block(54, cursor_y, "Monthly Fee", f"{student.monthly_fee:.2f}")
        cursor_y = add_wrapped_block(54, cursor_y, "Address", student.address, width=58)

        footer_y = max(96, cursor_y - 24)
        lines.append(f"0.80 0.84 0.90 RG 54 {footer_y + 10:.2f} m 541 {footer_y + 10:.2f} l S")
        add_text(54, footer_y - 4, "Generated by Parishilon Academy", 9, (0.43, 0.47, 0.52))
        add_text(390, footer_y - 4, _datetime.datetime.now().strftime("%d %b %Y, %I:%M %p"), 9, (0.43, 0.47, 0.52))

        return "\n".join(lines)

    def _build_fee_statement_content_stream(self, student: Student, payment_records: list[dict[str, object]]) -> str:
        lines: list[str] = []

        def add_text(x: float, y: float, text: str, size: int = 11, color: tuple[float, float, float] = (0.0, 0.0, 0.0)) -> None:
            escaped_text = self._escape_text(self._ascii_safe(text))
            lines.append(f"BT /F1 {size} Tf {color[0]:.3f} {color[1]:.3f} {color[2]:.3f} rg 1 0 0 1 {x:.2f} {y:.2f} Tm ({escaped_text}) Tj ET")

        def draw_line(x1: float, y1: float, x2: float, y2: float, color: tuple[float, float, float] = (0.75, 0.78, 0.84)) -> None:
            lines.append(f"{color[0]:.3f} {color[1]:.3f} {color[2]:.3f} RG {x1:.2f} {y1:.2f} m {x2:.2f} {y2:.2f} l S")

        def draw_block(label: str, value: str, x: float, y: float, label_width: float = 120.0) -> None:
            add_text(x, y, f"{label}:", 11, (0.07, 0.11, 0.2))
            add_text(x + label_width, y, value, 11, (0.15, 0.18, 0.24))

        lines.append("0.11 0.30 0.85 rg 36 746 523 58 re f")
        add_text(54, 776, "Fee Statement", 18, (1, 1, 1))
        add_text(54, 758, "Parishilon Academy", 10, (0.93, 0.96, 1))
        add_text(470, 776, f"S.I.N: {student.sin}", 10, (1, 1, 1))

        details_top = 714
        details = [
            ("Student Name", student.student_name),
            ("Father Name", student.father_name),
            ("Mother Name", student.mother_name),
            ("Phone Number", student.phone),
            ("School Name", student.school),
            ("Class", student.class_name),
            ("Admission Date", student.admission_date),
            ("Monthly Fee", f"{student.monthly_fee:.2f}"),
            ("Address", student.address),
        ]

        cursor_y = details_top
        for label, value in details:
            if label == "Address":
                wrapped_lines = wrap(self._ascii_safe(value), width=58) or [""]
                add_text(54, cursor_y, f"{label}:", 11, (0.07, 0.11, 0.2))
                add_text(174, cursor_y, wrapped_lines[0], 11, (0.15, 0.18, 0.24))
                cursor_y -= 18
                for continuation in wrapped_lines[1:]:
                    add_text(174, cursor_y, continuation, 11, (0.15, 0.18, 0.24))
                    cursor_y -= 18
            else:
                draw_block(label, value, 54, cursor_y)
                cursor_y -= 18

        table_top = cursor_y - 8
        draw_line(36, table_top, 559, table_top)
        draw_line(36, table_top - 24, 559, table_top - 24)

        columns = [
            (36, 88, "Month"),
            (124, 88, "Date"),
            (202, 120, "Amount"),
            (322, 160, "Note"),
            (482, 77, "Status"),
        ]
        for x, width, heading in columns:
            add_text(x + 6, table_top - 16, heading, 10, (0.07, 0.11, 0.2))
            draw_line(x, table_top, x, table_top - 24)
        draw_line(559, table_top, 559, table_top - 24)

        row_y = table_top - 44
        row_height = 22
        max_rows = 14
        total_paid = 0.0

        if not payment_records:
            add_text(54, row_y, "No fee payments have been recorded yet.", 10, (0.35, 0.38, 0.45))
            row_y -= row_height
        else:
            for index, record in enumerate(payment_records[:max_rows], start=1):
                month = str(record.get("payment_month", ""))
                date_value = str(record.get("payment_date", ""))
                amount = float(record.get("amount", 0.0))
                note = self._ascii_safe(str(record.get("note", "")))
                status = "Paid"
                total_paid += amount

                values = [month, date_value, f"{amount:.2f}", note, status]
                widths = [88, 78, 120, 160, 77]
                x_positions = [36, 124, 202, 322, 482]
                for x, width, value in zip(x_positions, widths, values):
                    clipped = value[: int(width / 6)]
                    add_text(x + 6, row_y, clipped, 10, (0.15, 0.18, 0.24))
                    draw_line(x, row_y + 8, x, row_y - 14)
                draw_line(559, row_y + 8, 559, row_y - 14)
                draw_line(36, row_y - 14, 559, row_y - 14)
                row_y -= row_height

        summary_y = max(100, row_y - 10)
        draw_line(36, summary_y + 18, 559, summary_y + 18)
        add_text(54, summary_y, f"Total Paid: {total_paid:.2f}", 11, (0.07, 0.11, 0.2))
        add_text(350, summary_y, f"Balance: {max(0.0, student.monthly_fee * max(len(payment_records), 1) - total_paid):.2f}", 11, (0.07, 0.11, 0.2))
        add_text(54, 80, "Generated by Parishilon Academy", 9, (0.43, 0.47, 0.52))
        add_text(390, 80, _datetime.datetime.now().strftime("%d %b %Y, %I:%M %p"), 9, (0.43, 0.47, 0.52))

        return "\n".join(lines)

    def _build_pdf_bytes(self, content_stream: str) -> bytes:
        stream_bytes = content_stream.encode("latin-1")
        objects: list[bytes] = []

        def obj(payload: str | bytes) -> bytes:
            if isinstance(payload, str):
                payload = payload.encode("latin-1")
            return payload

        objects.append(obj("<< /Type /Catalog /Pages 2 0 R >>"))
        objects.append(obj("<< /Type /Pages /Kids [3 0 R] /Count 1 >>"))
        objects.append(obj(f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {self.PAGE_WIDTH:.2f} {self.PAGE_HEIGHT:.2f}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"))
        objects.append(obj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"))
        objects.append(obj(f"<< /Length {len(stream_bytes)} >>\nstream\n" + content_stream + "\nendstream"))

        pdf = bytearray()
        pdf.extend(b"%PDF-1.4\n")

        offsets = [0]
        for index, payload in enumerate(objects, start=1):
            offsets.append(len(pdf))
            pdf.extend(f"{index} 0 obj\n".encode("latin-1"))
            pdf.extend(payload)
            pdf.extend(b"\nendobj\n")

        xref_start = len(pdf)
        pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("latin-1"))
        pdf.extend(b"0000000000 65535 f \n")
        for offset in offsets[1:]:
            pdf.extend(f"{offset:010d} 00000 n \n".encode("latin-1"))

        pdf.extend(
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_start}\n%%EOF\n".encode(
                "latin-1"
            )
        )
        return bytes(pdf)

    def _escape_text(self, text: str) -> str:
        return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    def _ascii_safe(self, text: str) -> str:
        normalized = text.replace("\n", " ").replace("\r", " ")
        return normalized.encode("ascii", "ignore").decode("ascii")